# Generated by Django 3.0.6 on 2023-05-12 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_user_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(default=1)),
                ('AID', models.IntegerField(default=1)),
                ('totalAmount', models.IntegerField(default=0)),
                ('airline', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='order_id',
            field=models.IntegerField(default=1),
        ),
    ]
