# Generated by Django 3.0.6 on 2023-05-12 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20230512_0254'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='invoice',
            new_name='invoice_detail',
        ),
    ]
