# Generated by Django 3.0.6 on 2023-05-12 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20230512_0301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice_detail',
            old_name='order_id',
            new_name='orderid',
        ),
    ]
