# Generated by Django 3.0.6 on 2023-05-12 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_auto_20230512_0418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='realname',
            field=models.CharField(max_length=256),
        ),
    ]
